### PR TITLE
Fix NBT Match where tag is empty but exists

### PR DESCRIPTION
**Pull request by spacebuilder2020**
I discovered that when trying to take items like Sunarium out of a reactor, it would not extract with a basic extractor.  When testing in single player with remote debugging, I found that the item that was being compared had an empty tag map object instead of a null object.  Solution is to check if tag is empty in addition to the null check.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@spacebuilder2020 you need to run spotless

**Comment by Glease** [comment]
I'd prefer to make those items to not generate empty tags

**Comment by spacebuilder2020** [comment]
Yea, I would agree with you.   Not sure if it is an interaction with the reactor or something different but I noticed once the item has moved to a chest and I put it back it no longer has a tag.

**Comment by spacebuilder2020** [comment]
Interestingly enough, on never versions instead of checking for a null, they are checking to see if the tags are equal.

Not sure what implementation is better to be honest.

https://github.com/SleepyTrousers/EnderIO-1.5-1.12/blob/9249b7e01fd73c7bc92a2fd60e768c1ef5b39fd3/enderio-base/src/main/java/crazypants/enderio/base/filter/item/ItemFilter.java#L164

**Comment by Glease** [comment]
they [do ignore empty tags](https://github.com/SleepyTrousers/EnderIO-1.5-1.12/blob/9249b7e01fd73c7bc92a2fd60e768c1ef5b39fd3/enderio-base/src/main/java/crazypants/enderio/base/filter/item/ItemFilter.java#L174) though. I'd say the their implementation is a bit more robust (e.g. when filter item has empty tag map and looks much better.

It's hard to tell how that item could have an empty tag map (I'm the author of sunnarium/glowstone rod myself and I can't tell at all why it could ever have an empty tag map, or have any tag at all) so perhaps we just ignore it for now.

**Comment by spacebuilder2020** [comment]
Yea, I agree.  The strange thing is it worked in the past on the server but when I was messing with it today, the same setup (basic filter) no longer worked and it was working on 2.4.0...

**Review by Glease — APPROVED** [review]
should be safe to merge

**Pull request merged**
