### PR TITLE
Change default connection mode of fluid conduits

### PR DESCRIPTION
**Pull request by Alexdoru**
Right now when you place a fluid conduit, it will be in insert & extract mode by default which means if you have any fluid getting pushed into the network as you place the conduits, the fluids will get pushed to any tank touching the conduit.

This pr changes the default mode to be extract only just like it does with item conduits.

Note that any conduit that is already placed in the world and kept with default setting will see its setting changed to extract only when loading the world with this new update. So it might break some setups for players that used fluid conduits with default setting, but honestly who keeps default settings ?

### CODE REVIEW

**Review by Pilzinsel64 — DISMISSED** [review]

**Comment by Alexdoru** [comment]
I don't know why the build failed, the formatting of the code I pushed should be correct regarding the spotless checks

**Comment by Dream-Master** [comment]
@Alexdoru wild card imports need to rewok

**Review by Pilzinsel64 — DISMISSED** [review]

**Comment by Pilad** [comment]
Can you still fix it like it was before? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14600

**Comment by Alexdoru** [comment]
> Can you still fix it like it was before? [GTNewHorizons/GT-New-Horizons-Modpack#14600](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14600)

ok that's interesting but it has nothing to do with my pr, could you not block the merging of my PR for something un-related @Pilzinsel64

**Review by Pilzinsel64 — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
I am sorry, I had no idea that this was meant for something else. I just had this minor change in mind and no clue a out the issue. :/

**Comment by Pilzinsel64** [comment]
Hey, I approved an PR a week ago but I just recolonized now that the change is more intensive then I thought.

It breaks ME conduits (they just don't work if not IN_OUT) and the default behavior of Power Cables wich is intended to be as IN_OUT by default except in special cases. In case of In_OUT, all Energy Conduits build a network without the use of their internal capacitor wich is more efficient and let special machines of EIO work better.

I suggest that they both, Energy Conduits and ME Conduts, should need an overwrite to restore the default behavior to IN_OUT of them, in my opinion. What do you think? @eigenraven @Alexdoru @Pilad @everyonewhoisinterested

Sadly, I have not the time at the moment and just reverted the change in my own fork to get all our Bases on our Server to work again.

**Comment by Alexdoru** [comment]
> Hey, I approved an PR a week ago but I just recolonized now that the change is more intensive then I thought.
> 
> It breaks ME conduits (they just don't work if not IN_OUT) and the default behavior of Power Cables wich is intended to be as IN_OUT by default except in special cases. In case of In_OUT, all Energy Conduits build a network without the use of their internal capacitor wich is more efficient and let special machines of EIO work better.
> 
> I suggest that they both, Energy Conduits and ME Conduts, should need an overwrite to restore the default behavior to IN_OUT of them, in my opinion. What do you think? @eigenraven @Alexdoru @Pilad @everyonewhoisinterested
> 
> Sadly, I have not the time at the moment and just reverted the change in my own fork to get all our Bases on our Server to work again.

if changing the fluid conduits affects the energy & ME conduits, it sounds like it's the energy & ME conduits that needs to be changed

**Comment by Alexdoru** [comment]
@Pilzinsel64  https://github.com/GTNewHorizons/EnderIO/pull/135

**Comment by Pilzinsel64** [comment]
Alright, good job! @Alexdoru

**Pull request merged**
