### PR TITLE
Add staff of teleportation

### PR DESCRIPTION
**Pull request by D-Cysteine**
I was feeling inspired to add a new super-teleport item, so here it is. This is meant as an endgame, extremely powerful tool for moving around large bases. In addition to this item, I also added support for teleporting to travel anchors that are outside of render range, which will work for the regular staff of travelling as well, if the config for it is increased to beyond render range.

---

On shift-right-click, it teleports to travel anchors and telepads, but the range has been increased to 2048 blocks. This is meant to be used with Journeymap waypoints to show you where to click, as travel anchors won't render at such huge ranges.

On right-click, the staff will do a raycast to where the player is looking, with distance of up to 512 (I believe this is done client-side, so it is limited by the player's render distance and locally loaded chunks). If the raycast hits a block, then the player is teleported to that block, with a slight buffer distance so you aren't hitting the wall with your face. If the raycast does not hit any blocks, then the player will instead be teleported 64 blocks (no cooldown; spam for quick travel). If the raycast hits a block that is within 3 distance, then the staff will attempt to teleport the player to the other side of a wall, with distance up to 16.

Just like the Creative Staff of Travelling, this staff has infinite energy.

There are a few potential issues with this:
1. The server keeps track of all travel anchors and tests them all upon a teleport attempt. This is just some vector math and trigonometry to calculate the distance and angle, but I am not sure if it will be slow if there are a very large number of travel anchors on the server.
2. The player can use this staff to teleport through even warded glass, which the normal staff specifically checks for and won't teleport through. Though if needed, we can add that check to the new teleport method.
3. There's some client-side rendering code which sets render distance for travel anchors equal to the square of the max teleport distance. For this staff, that distance is (by default) 2048, so it'll get very large as it is being squared. I didn't notice any performance issues, or any effect at all on render distance due to this, but it could potentially do some weird stuff, especially if we increase that distance to an even bigger number than 2048.

---

I didn't add any recipes for this item yet, as I don't feel qualified to come up with a fair recipe. Anyone who has a better idea of a good recipe, please add one for it. Also, the default config values could be adjusted, if other numbers would be better.

### CODE REVIEW

**Comment by boubou19** [comment]
maybe merge this with the infinte travel staff no? as this one is gated at UV tier. Gating another higher wouldn't make much sense i think

**Comment by Dream-Master** [comment]
The creative staff need to be use as ingredient because this staff is more powerfull.

**Comment by Dream-Master** [comment]
or replace it yea. Maybe better more

**Comment by boubou19** [comment]
shifting the recipe a tier above then?

**Comment by D-Cysteine** [comment]
> maybe merge this with the infinte travel staff no? as this one is gated at UV tier. Gating another higher wouldn't make much sense i think

Do you want me to do this in the code, or did you mean something like just editing the recipe to give the new staff rather than the old one?

**Comment by boubou19** [comment]
Basically just replace the creative staff with your version. Much more useful. Recipe is done in coremod and imo it does not need to be touched, aside from making sure it gives the correct item if you rename it in EIO's side.

**Comment by D-Cysteine** [comment]
Alright, I removed the old staff. I'll make a PR in coremod to update the recipe output. Do you know how to make old worlds with the creative staff automatically replace it with the new staff?

**Comment by boubou19** [comment]
what i would have done is to hijack the code of the previous creative staff and i would have put all your additions into it. But i guess you can use the missing mapping event and reroute creative staff mapping to the new staff.

**Comment by D-Cysteine** [comment]
> what i would have done is to hijack the code of the previous creative staff and i would have put all your additions into it. But i guess you can use the missing mapping event and reroute creative staff mapping to the new staff.

I thought it would be cleaner to just do a full rename / replacement, but writing the remap code ended up taking a lot longer than I expected because I made a dumb mistake =(
Oh well, it's done and works now

**Comment by Dream-Master** [comment]
works for me ingame

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
