### PR TITLE
Add more ender fluid conduit types

### PR DESCRIPTION
**Pull request by D-Cysteine**
Expansion of:
 * https://github.com/GTNewHorizons/EnderIO/pull/33

Replaces the advanced ender fluid conduit with four tiers of ender fluid conduit (five total counting the regular ender fluid conduit). Here's the current default throughputs:
 1. Ender Fluid Conduit
   a) 4,000 L/s extract
   b) 16,000 L/s max throughput
 2. Crystalline Ender Fluid Conduit
   a) 20,000 L/s extract
   b) 80,000 L/s max throughput
 3. Crystalline Pink Slime Ender Fluid Conduit
   a) 40,000 L/s extract
   b) 160,000 L/s max throughput
 4. Melodic Ender Fluid Conduit
   a) 200,000 L/s extract
   b) 800,000 L/s max throughput
 5. Stellar Ender Fluid Conduit
   a) 400,000 L/s extract
   b) 1,600,000 L/s max throughput

How do these values look?

Also, the new textures are not very good. I have no art skills, so I just did a low-quality color swap of the original ender fluid conduit texture. If someone with better art skills wants to make some better ones, that would be appreciated.

### CODE REVIEW

**Comment by Sphyix** [comment]
Proposal:
Use gregtech pumps as crafting components and match their speed, it could go from HV to ZPM.
Cost could be 1 pump + other pump-tier material for multiple conduits.
This way conduit speed is tiered with GT.

It would probably make conduits a bit more expensive overall, but more in line with the rest of the pack for speed and tiering.

**Comment by Glease** [comment]
Using *You are gonna hate this* series component in recipe is the top most mistake in LogisiticsPipes integeration. It made the pipes unreasonably expensive and not a single person would ever use them. Don't repeat this mistake.

**Comment by Sphyix** [comment]
Idea was to make them worth it for short runs, but not for complex systems.

Like if I need a stack of them to go 64 blocks away, it's gonna be expensive and I'm better off with ender tanks, but if I need to connect 2 machines that are 3-4 blocks away it'll be cheaper to use eio.

It could avoid big networks and make them a lot more useful for the higher speeds on short runs.

**Comment by boubou19** [comment]
i have a question @D-Cysteine : it may sound obvious, what happens if you mix different ender fluid conduits throughput wise? Because if the limitations are done only on the extraction node, then players can simply for exemple put highest tier conduit where an extraction is needed then put normal ender fluid conduits on the rest of the network. Do we want to allow this? For me it would make sense to allow this as it will encourage people to think where fast extraction is needed, and that would leave some space for pricey recipes.

But if we want to reduce size of the networks because of lag, then we shouldn't allow such mix.

**Comment by D-Cysteine** [comment]
Right now, you cannot connect fluid conduits of different tiers. I'm not sure how easy it would be to change that, but I think the assumption that all nodes in a network are identical (same extract and I/O rates) is baked into the logic, so might require a substantial re-write.

**Comment by Dream-Master** [comment]
Let’s test it on zeta

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
