### PR TITLE
Allow blinking onto the roof

### PR DESCRIPTION
**Pull request by miozune**
I'm not sure if this is 100% fine, so added config to disable this feature.

https://user-images.githubusercontent.com/40035906/164971847-abbbedbb-cf56-4f7f-a148-1116b1ab8abe.mp4

### CODE REVIEW

**Review by repo-alt — COMMENTED** [review]
That may result in like being unable to blink to the cave ceiling e,g. Perhaps just swap the Y and Y-1 blinks?

**Comment by Dream-Master** [comment]
will this make you travell on the nether roof top :) ?

**Comment by repo-alt** [comment]
Yes it will (in some places). Not like you are unable to to that via some other means

**Comment by miozune** [comment]
> That may result in like being unable to blink to the cave ceiling e,g. Perhaps just swap the Y and Y-1 blinks?

Wdym by cave ceiling? Teleport inside ceiling or near the surface of ceiling?
Swapping won't work, blinking to roof is realized by iterating over `doBlinkAround` twice.


> will this make you travell on the nether roof top :) ?

No you can't, forbidden in config `travelStaffBlinkBlackList`.

**Comment by Dream-Master** [comment]
A nice travel on the top of the nether would be cool :)

**Comment by miozune** [comment]
If you want to pass through bedrock, remove bedrock from config `travelStaffBlinkBlackList` and set `travelStaffBlinkThroughUnbreakableBlocksEnabled` to true.

**Comment by LewisSaber** [comment]
This staff is mainly used to travel between blocks, i personally use it to go under floor and back

**Comment by repo-alt** [comment]
> swapping won't work, blinking to roof is realized by iterating over doBlinkAround twice (or more).
Yes, so why not swap these 2 calls, first trying higher location?

**Comment by miozune** [comment]
Well it won't hurt

**Comment by repo-alt** [comment]
So, now config option is probably unnecessary? When the check order is from top to bottom, blink to the roof is possible, and the other behaviour is unchanged.  Arguably, the checking order change may be made optional, if there are people that _do not_ want to blink to upper floors

**Comment by miozune** [comment]
No. `doBlinkAround` works like this:
### first iteration
sample.y == 10
if (y == sample.y) -> Fail
if (y == sample.y + 1) -> Fail
if (y == sample.y - 1) -> Succeed. Player teleports under the roof. We want to skip this.
### second iteration
sample.y == 11
if (y == sample.y) -> Fail
if (y == sample.y + 1) -> Succeed. Player teleports on the roof.

**Comment by repo-alt** [comment]
Ah, I didn't look at the surrounding code. Ok then.

**Review by repo-alt — APPROVED** [review]

**Pull request merged**
