### PR TITLE
Ultra Dense ME Conduits

### PR DESCRIPTION
**Pull request by Pilzinsel64**
Adds working Ultra Dense ME Conduits (128 channels) with an working recipe. Disabled by default, but can be enabled via the config `enableMeUltraDenseConduits`.

Not sure if two booleans are the fine thing here, but it works well here, styled like AE2. If you prefer e.g. an int, just tell me to change it.

grafik
grafik

# Todo
- [ ] Adjust `canConnectToExternal()` to behav more like Backbones from AE2 and only try to connect to other ME Cables (any tier). and AE2 Dense Parts
- [ ] *(Check stability of AE2 Backbone functionality until merging?)*

### CODE REVIEW

**Comment by boubou19** [comment]
backbone cables are bugged, not a fan of making it more accessible.

**Comment by Pilzinsel64** [comment]
> backbone cables are bugged, not a fan of making it more accessible.

True, that's why I added them via Ender IO as they seems to work a little bit better, and disabled by default.
I'll update the mod tonight on our server and work with them the next few days. We will see any disadvantages as there are people with a lot knowledge in AE2 and Ender IO.

**Comment by Dream-Master** [comment]
@boubou19 @Pilzinsel64 maybe a rework of the backbone cable will fix it but have a 128 channel cable is a nice thing and GTNH exclusive.

**Comment by Pilzinsel64** [comment]
@Dream-Master True. But the AE2 code is very complex and I'm mostly a noob in Java and minecraft modding in genera. :D Also not sure what the known bugs with backbones are.

## Probably-Bug in AE2

In the AE2 code I've found probably one bug. See here:
grafik
grafik

## Maybe-Bug in AE2

And one "maybe" bug where I'm not sure if this is intended or not. The Backbone cables from AE2 (and also the Ultra Dense from Ender IO now) don't connect with anything except other cables. So you need to connect a Ultra Dense/Backbone cable using four Dense cables to the controller or to a maschine.
grafik
grafik
grafik
grafik
grafik
grafik
grafik

## As a first review after we played around with them for several hours on our server

The Ender IO Ultra Dense cables seems to work fine. But again, I'm not sure if Backbones cables should or shouldn't connect to anything except other cables. The Ender IO Ultra Dense cables also doesn't really connect, but shows that they do. That's a bug in Ender IO if the current behavior (backbones only connects to other cables) is intended.

## The end

Again, @Dream-Master what do you think is the correct behavior for the Backbone's? What are even the bugs for Backbones? I didn't found any "real" bug yet, except what I menoined here. Can you please tell me? Should we do further talk on Discord maybe? If yes, just ping me there.

**Comment by Dream-Master** [comment]
@Pilzinsel64 the bug was not reported by me. I have no clue what exactly is broken but i hear it not work or is broken.

**Comment by Pilzinsel64** [comment]
How sad. :/ But thank you anyway.
Should I just submit the AE2 changes as PR and see what's coming next?

Btw, I made the Backbone Cables craftable on my server, so let's see how good they work after a while.

**Comment by Dream-Master** [comment]
@Pilzinsel64 sure.

**Comment by Pilzinsel64** [comment]
A new state of things: After a few days testing we disabled the Ultra Dense for now. After a server restart they seems to loose their connection probably, but didn't tested again.

However, the Backbone functionality seems to really need a bigger rework. But however, there are a lot of decisions for I want and can't do.

I would leave this open for now as normal PR and not as Draft, if this is ok. As soon as the AE2 Backbones got a rework this PR should still mostly be valid and can be probably merged without other adjustments.

Mostly independent to this PR the ME Conduits in general needs a few optimizations I'm also not able to do probably. They sometimes have a inconstistent behavior at "shouldConnect()" and "shouldConnectToExternal()". Also they do not expected imperformant chunkloading that should be fixed. However, I still haven't found the final issue for this and have not the time for to investigate more time for.

**Comment by Dream-Master** [comment]
> A new state of things: We tried using them for a few days but disbaled then again until they are officially merged. Not sure if a server restart breaks their connection, I had no time to check that. Maybe someone want to review them. :)
> 
> Possible problems yet:
> 
> * A server restart might disable the connection between dense and ultra dense cables (?)
> * The ME Ultra Dense Conduits would need some adjustments at `canConnectToExternal()` probably to not show a connection where no connection is.
> 
> However, the Backbone functionaility from AE2 seems to be buggy in some cases and shouldn't be used at all. But as they are even craftable in GTNH I want to keep this PR as long as nobody close it. But feel free to do, if you want, or review and merge it. Your decision.
> 
> Refrence conversion on Discord: https://discord.com/channels/181078474394566657/603348502637969419/1084901791038177400

I hope we can fix backbone cables and add your pr as well. Not sure who can help here ? @asdflj @firenoo @repo-alt @GlodBlock @Glease @eigenraven

**Comment by repo-alt** [comment]
To debug backbone cable problems it would be nice to have a world download with some reasonable-sized AE2 system, where backbone cable problems can be reliably reproduced. So far I had only one world dowload where the base takes dozens of chunks with thousands of devices (it also uses EC2 which doesn't help at all)

**Comment by Dream-Master** [comment]
@repo-alt we have enough end game bases and enough endgame players. if we make a call people can use this cables in there setting we get a world with this backbone cables i would guess?

**Comment by repo-alt** [comment]
Eh, the point is - endgame bases are a bit usesless, because their topology is usually insane, and to debug something on them is not very feasible. What would be useful is if someone would use the cables while their base is still reasonable-sized, and will discover a situation where some bugs are reliably reproducible.

**Comment by Dream-Master** [comment]
ok undestand. Is there a way to reproduce the bugs/issues or is there some open issue decribe it? i hear we have problems but i dont have more infos.

**Comment by repo-alt** [comment]
Apart from that world downoad I only had reports in discord, so definitely there are bugs, but I don't know how to easily reproduce them. Reports looked like: parts of the network are not visible, network boot up time is incredibly long, etc.

**Comment by firenoo** [comment]
Let's open a dedicated issue on the modpack to track/discuss these.

**Comment by Pilzinsel64** [comment]
> i hear we have problems but i dont have more infos.

> To debug backbone cable problems it would be nice to have a world download with some reasonable-sized AE2 system, where backbone cable problems can be reliably reproduced.

The most bugs I also just heard. For us we had no bigger problems while testing but see a few things that feels mostly random. Also my personal bugs mostly depends on how Backbones are intended to work and connect to what.

E.g.
- Used Channels count needs long to update
_(sometimes, so not really reproduceable)_
- Ender IO and AE2 cables have different behaviors on how they connect to other Nodes
_(probably fixed with latest commit here, should remove the most inconstancy)_
- A user has a problem with P2P. Whenever he trieds to use Backbones _behind_ the P2P network it has problems with channels showing on the cables / updating.
_(Can provide a detailed description soon, with a small test work download.)_
- ~A server restart might break Backbone connections~
_(might be Ender IO but I tested again today and there are no problems)_
- Sometimes Backbones won't connect, but this also might be a problem with Ender IO that is probably fixed with last commit

... and probably more. I just hear so many people saying they are buggy and you shouldn't use them. That probably affected my tests a little bit. But as I said a week ago, the code is complexe but seems complete. Depending on how they should work, they have more bugs or adjustments needed or less.

As soon we run into a problem we will test around and hopefully reproduce any problem we get in the future. I'll come back to you then.

**Comment by Pilzinsel64** [comment]
Btw, my last commit seems to work well and consistent on my testworld here. Want to test it on our test server that always holds a backup from the previus day. I'll let you know how the conduits work there.
[New World-.zip](https://github.com/GTNewHorizons/EnderIO/files/10969477/New.World-.zip) _(ensure to install AE2 in order to be able to load and test this world)_

**Comment by firenoo** [comment]
> A user has a problem with P2P. Whenever he trieds to use Backbones behind the P2P network it has problems with channels showing on the cables / updating.
(Can provide a detailed description soon, with a small test work download.)

Is this with the memory card (AE2) or advanced memory card (BetterP2P), and does this happen with EnderIO cables in general?

**Comment by Pilzinsel64** [comment]
@firenoo This does happen only with AE2 cables and the default memory carf. The user doesn't use the Ender IO ME Conduits and also not the BetterP2P Memory Card.

**Review by eigenraven — APPROVED** [review]

**Comment by Pilzinsel64** [comment]
🥳
Side node for GTNH modpack: As the Backbones have a reciped, the [Ultra Dense also needs one](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/c41157db861dd4a0f5bb9c1b0dc33f4e97ca1dd8/scripts/Ender-IO.zs#L451-L454). I'm not fimilar with GregTech materials, so that needs to do someone else.

**Pull request merged**
