### PR TITLE
Adds new tier of ender fluid conduit. It's missing working with the fluid filters, need help with that

### PR DESCRIPTION
**Pull request by Prometheus0000**
It does transfer the fluid, but it doesn't show the filter or the button on the right.
image
Normal one.
image
I don't know how to do the visual stuff. I could recolor something, but I don't know how to get it to point at it.
image

The code is too complicated for me to understand 90% of it, so I just copied it instead of trying overriding, since I'm sure I'd fail at it. The only difference I want is the name, appearance and the amount of I/O.

Could someone tell me what I'm missing?

### CODE REVIEW

**Comment by Prometheus0000** [comment]
It still doesn't show the fluid filter or extract button on the GUI, but the rest of it works.

**Comment by LewisSaber** [comment]
what is speed?

**Comment by Prometheus0000** [comment]
```public static int enderFluidConduitExtractRate = 200;
  public static int enderFluidConduitMaxIoRate = 800;
  public static int enderFluidConduitMaxIoRate = 800;
  public static int enderFluidConduitAdvancedExtractRate = 1000; (new)
  public static int enderFluidConduitAdvancedMaxIoRate = 4000; (new)
  public static int advancedFluidConduitExtractRate = 100;
  public static int advancedFluidConduitExtractRate = 100;
  public static int advancedFluidConduitMaxIoRate = 400;
  public static int advancedFluidConduitMaxIoRate = 400;
  public static int fluidConduitExtractRate = 50;
  public static int fluidConduitExtractRate = 50;

The numbers are temp for now. It depends on when we would tier it. Same for the recipe.

**Comment by Prometheus0000** [comment]
The fluid filter stuff is in src/main/java/crazypants/enderio/conduit/gui/LiquidSettings.java and src/main/java/crazypants/enderio/conduit/gui/PacketFluidFilter.java 

It also needs a real and not temp recipe, as well as a decided I/O and extraction speed. I'm thinking LuV/ZPM? I don't think we want to make it replace GT pipes or anything, but having it be more useful for automatic processing stuff for longer would be nice.

**Comment by dvdmandt** [comment]
There are some spots in LiquidSettings and PacketFluidFilter and possibly others that check if the conduit is an instance of EnderLiquidCondiut, and if so casts to it and does stuff. It would be possible to deal with those things as well, but I wonder if it wouldn't be easier to deal with inheritance after all, or do some refactoring and add explicit tiering support so that we could add more in the future without copy/paste hell.

**Comment by Prometheus0000** [comment]
The casting is what confused me, I don't even know what it means except that I can't do an if statement. If you want to change something that would make this better/possible feel free. I think too many tiers might not be a good idea since we don't want people forsaking the GT pipes completely (or do we?) but having more would probably be fine.

**Comment by Dream-Master** [comment]
@dvdmandt feel free to change this pr and add more or better code. Not everyone is experienced with coding (includes me as well) but we have ideas to add more stuff.

**Comment by Dream-Master** [comment]
@dvdmandt ah didn't  see you do a pr as well 😎

**Comment by Dream-Master** [comment]
@D-Cysteine maybe you can help us here

**Comment by Dream-Master** [comment]
see https://github.com/GTNewHorizons/EnderIO/pull/33

**Pull request closed without merging**
